[Unit]
Requires=sovereign-data-expand.service
RequiresMountsFor=/data
After=local-fs.target sovereign-data-expand.service containerd.service
ConditionPathIsMountPoint=/data

[Service]
ExecStartPre=/usr/bin/install -d -m 0711 /data/docker
