#!/bin/bash

set -eu
"$BDEBSTRAP_HOOKS/enable-units" "$1" sovereign-proof.service
"$BDEBSTRAP_HOOKS/enable-units" "$1" sovereign-pihole-artifact.service
"$BDEBSTRAP_HOOKS/enable-units" "$1" sovereign-pihole-import.service
